export const criteria = [
	{
		criteriaTitle: "Name, Role, Value",
		wcag: "4.1.2",
		wcagLink: "https://www.w3.org/TR/WCAG21/#name-role-value",
		en: "9.4.1.2",
		webb: "Namn, roll, värde",
		webbLink:
			"https://www.digg.se/webbriktlinjer/alla-webbriktlinjer/se-till-att-komponenter-fungerar-i-hjalpmedel",
		text: "For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined; states, properties, and values that can be set by the user can be programmatically set; and notification of changes to these items is available to user agents, including assistive technologies.",
		principle: "robust",
	},
]
