export const criteria = [
	{
		criteriaTitle: "Non-text Content",
		wcag: "1.1.1",
		wcagLink: "https://www.w3.org/TR/WCAG22/#non-text-content",
		en: "9.1.1.1",
		webb: "Beskriv med text allt innehåll som inte är text",
		webbLink:
			"https://www.digg.se/webbriktlinjer/alla-webbriktlinjer/beskriv-med-text-allt-innehall-som-inte-ar-text",
		text: "All non-text content that is presented to the user has a text alternative that serves the equivalent purpose [...].",
		principle: "percievable",
		level: "A",
	},
	{
		criteriaTitle: "Use of Color",
		wcag: "1.4.1",
		wcagLink: "https://www.w3.org/TR/WCAG22/#use-of-color",
		en: "9.1.4.1",
		webb: "Använd inte enbart färg för att förmedla information",
		webbLink:
			"https://www.digg.se/webbriktlinjer/alla-webbriktlinjer/anvand-inte-enbart-farg-for-att-formedla-information",
		text: "Color is not used as the only visual means of conveying information, indicating an action, prompting a response, or distinguishing a visual element.",
		principle: "percievable",
		level: "A",
	},
	{
		criteriaTitle: "Contrast (Minimum)",
		wcag: "1.4.3",
		wcagLink: "https://www.w3.org/TR/WCAG22/#contrast-minimum",
		en: "9.1.4.3",
		webb: "Använd tillräcklig kontrast mellan text och bakgrund",
		webbLink:
			"https://www.digg.se/webbriktlinjer/alla-webbriktlinjer/anvand-tillracklig-kontrast-mellan-text-och-bakgrund",
		text: "The visual presentation of text and images of text has a contrast ratio of at least 4.5:1, except for the following:",
		text2: "Large Text. Large-scale text and images of large-scale text have a contrast ratio of at least 3:1.",
		text3: "Incidental. Text or images of text that are part of an inactive user interface component, that are pure decoration, that are not visible to anyone, or that are part of a picture that contains significant other visual content, have no contrast requirement.",
		text4: "Logotypes. Text that is part of a logo or brand name has no contrast requirement.",
		principle: "percievable",
		level: "AA",
	},
	{
		criteriaTitle: "Non-text Contrast",
		wcag: "1.4.11",
		wcagLink: "https://www.w3.org/TR/WCAG22/#non-text-contrast",
		en: "9.1.4.11",
		webb: "Använd tillräckliga kontraster i komponenter och grafik",
		webbLink:
			"https://www.digg.se/webbriktlinjer/alla-webbriktlinjer/anvand-tillrackliga-kontraster-i-komponenter-och-grafik",
		text: "The visual presentation of the following have a contrast ratio of at least 3:1 against adjacent color(s):",
		text2: "User Interface Components. Visual information required to identify user interface components and states, except for inactive components or where the appearance of the component is determined by the user agent and not modified by the author;",
		text3: "Graphical Objects. Parts of graphics required to understand the content, except when a particular presentation of graphics is essential to the information being conveyed.",
		principle: "percievable",
		level: "AA",
	},
	{
		criteriaTitle: "Keyboard",
		wcag: "2.1.1",
		wcagLink: "https://www.w3.org/TR/WCAG22/#keyboard",
		en: "9.2.1.1",
		webb: "All funktionalitet ska kunna användas med tangentbord",
		webbLink:
			"https://www.digg.se/webbriktlinjer/alla-webbriktlinjer/all-funktionalitet-ska-kunna-anvandas-med-tangentbord",
		text: "All functionality of the content is operable through a keyboard interface without requiring specific timings for individual keystrokes, except where the underlying function requires input that depends on the path of the user's movement and not just the endpoints.",
		principle: "operable",
		level: "A",
	},
	{
		criteriaTitle: "Focus Order",
		wcag: "2.4.3",
		wcagLink: "https://www.w3.org/TR/WCAG22/#focus-order",
		en: "9.2.4.3",
		webb: "Ha en meningsfull fokusordning",
		webbLink:
			"https://www.digg.se/webbriktlinjer/alla-webbriktlinjer/ha-en-meningsfull-fokusordning",
		text: "If a Web page can be navigated sequentially and the navigation sequences affect meaning or operation, focusable components receive focus in an order that preserves meaning and operability.",
		principle: "operable",
		level: "A",
	},
	{
		criteriaTitle: "Target Size (Enhanced)",
		wcag: "2.5.5",
		wcagLink: "https://www.w3.org/TR/WCAG22/#target-size-enhanced",
		en: "N/A",
		webb: "Gör länkar, klickbara ytor och menyer användbara för alla",
		webbLink:
			"https://www.digg.se/webbriktlinjer/alla-webbriktlinjer/gor-lankar-klickbara-ytor-och-menyer-anvandbara-for-alla",
		text: "The size of the target for pointer inputs is at least 44 by 44 CSS pixels except when:",
		text2: "The target is available through an equivalent link or control on the same page that is at least 44 by 44 CSS pixels;",
		text3: "Inline. The target is in a sentence or block of text;",
		text4: "User Agent Control. The size of the target is determined by the user agent and is not modified by the author;",
		text5: "Essential. A particular presentation of the target is essential to the information being conveyed.",
		principle: "operable",
		level: "AAA",
	},
	{
		criteriaTitle: "Target Size (Minimum)",
		wcag: "2.5.8",
		wcagLink: "https://www.w3.org/TR/WCAG22/#target-size-minimum",
		en: "N/A",
		webb: "Gör länkar, klickbara ytor och menyer användbara för alla",
		webbLink:
			"https://www.digg.se/webbriktlinjer/alla-webbriktlinjer/gor-lankar-klickbara-ytor-och-menyer-anvandbara-for-alla",
		text: "The size of the target for pointer inputs is at least 24 by 24 CSS pixels, except where:",
		text2: "Equivalent. The function can be achieved through a different control on the same page that meets this criterion;",
		text3: "Inline. The target is in a sentence or its size is otherwise constrained by the line-height of non-target text;",
		text4: "User Agent Control. The size of the target is determined by the user agent and is not modified by the author;",
		text5: "Essential. A particular presentation of the target is essential or is legally required for the information being conveyed.",
		principle: "operable",
		level: "AA",
	},
	{
		criteriaTitle: "Labels or Instructions",
		wcag: "3.3.2",
		wcagLink: "https://www.w3.org/TR/WCAG22/#labels-or-instructions",
		en: "9.3.3.2",
		webb: "Skapa tydliga fältetiketter och ledtexter",
		webbLink:
			"https://www.digg.se/webbriktlinjer/alla-webbriktlinjer/skapa-tydliga-faltetiketter-ledtexter",
		text: "Labels or instructions are provided when content requires user input.",
		principle: "understandable",
		level: "A",
	},
	{
		criteriaTitle: "Error Suggestion",
		wcag: "3.3.3",
		wcagLink: "https://www.w3.org/TR/WCAG22/#error-suggestion",
		en: "9.3.3.3",
		webb: "Ge förslag på hur fel kan rättas till",
		webbLink:
			"https://www.digg.se/webbriktlinjer/alla-webbriktlinjer/ge-forslag-pa-hur-fel-kan-rattas-till",
		text: "If an input error is automatically detected and suggestions for correction are known, then the suggestions are provided to the user, unless it would jeopardize the security or purpose of the content.",
		principle: "understandable",
		level: "AA",
	},
	{
		criteriaTitle: "Name, Role, Value",
		wcag: "4.1.2",
		wcagLink: "https://www.w3.org/TR/WCAG22/#name-role-value",
		en: "9.4.1.2",
		webb: "Namn, roll, värde",
		webbLink:
			"https://www.digg.se/webbriktlinjer/alla-webbriktlinjer/se-till-att-komponenter-fungerar-i-hjalpmedel",
		text: "For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined; states, properties, and values that can be set by the user can be programmatically set; and notification of changes to these items is available to user agents, including assistive technologies.",
		principle: "robust",
		level: "A",
	},
]
